<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Cntryl.LexKey.Tests</AssemblyName>
    <RootNamespace>Cntryl.Keys.Tests</RootNamespace>
    <IsPackable>false</IsPackable>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CA1515;CA1707;CA2007</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Cntryl.Conventions.Testing.Analyzers" Version="1.0.0" />
    <PackageReference Include="Cntryl.Conventions.Testing.CodeFixes" Version="1.0.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.10.0" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="4.0.0" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/LexKey/LexKey.csproj" />
  </ItemGroup>
</Project>
